server:
  port: 8080

#消息队列
spring:
  rabbitmq:
    virtual-host: /
    host: 175.178.25.239
    port: 5672
    username: admin
    password: password
    #开启消息二次确认 生产者到交换机
    publisher-confirm-type: correlated
    #开启消息返回 生产者到队列
    publisher-returns: true
    #为 true则交换机处理消息到路由失败，则会返回给生产者
    template:
      mandatory: true
    #手工确认ack
    listener:
      direct:
        acknowledge-mode: manual
